// sdk/vue-ui/src/components/renderers/BadgeList.vue
<template>
  <div class="flex flex-wrap gap-1">
    <Badge
      v-for="(item, i) in visible"
      :key="i"
      variant="secondary"
      class="text-[11px] font-mono"
    >
      {{ String(item) }}
    </Badge>
    <Badge v-if="overflow > 0" variant="outline" class="text-[10px] text-muted-foreground">
      +{{ overflow }} more
    </Badge>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import Badge from '../ui/Badge.vue';

const MAX_ITEMS = 50;

const props = defineProps<{
  items: (string | number | boolean)[];
}>();

const visible = computed(() => props.items.slice(0, MAX_ITEMS));
const overflow = computed(() => props.items.length - MAX_ITEMS);
</script>

// sdk/react-ui/src/components/renderers/BadgeList.tsx
import { Badge } from "../ui/Badge";

const MAX_ITEMS = 50;

interface BadgeListProps {
  items: (string | number | boolean)[];
}

export function BadgeList({ items }: BadgeListProps) {
  const visible = items.slice(0, MAX_ITEMS);
  const overflow = items.length - MAX_ITEMS;

  return (
    <div className="flex flex-wrap gap-1">
      {visible.map((item, i) => (
        <Badge key={i} variant="secondary" className="text-[11px] font-mono">
          {String(item)}
        </Badge>
      ))}
      {overflow > 0 && (
        <Badge variant="outline" className="text-[10px] text-muted-foreground">
          +{overflow} more
        </Badge>
      )}
    </div>
  );
}
