// sdk/vue-ui/src/components/renderers/DataTable.vue
<template>
  <div class="space-y-1.5">
    <div v-if="meta && Object.keys(meta).length > 0" class="flex flex-wrap gap-1">
      <Badge
        v-for="[k, v] in Object.entries(meta)"
        :key="k"
        variant="outline"
        class="text-[10px] font-mono"
      >
        {{ k }}: {{ String(v) }}
      </Badge>
    </div>
    <div class="max-h-72 overflow-y-auto overflow-x-auto rounded-md border">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead
              v-for="col in columns"
              :key="col"
              class="font-mono text-[11px] whitespace-nowrap"
            >
              {{ col }}
            </TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow v-for="(row, i) in rows" :key="i">
            <TableCell v-for="col in columns" :key="col" class="text-[11px] font-mono">
              <CellValue :value="row[col]" />
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  </div>
</template>

<script setup lang="ts">
import Table from '../ui/Table.vue';
import TableHeader from '../ui/TableHeader.vue';
import TableBody from '../ui/TableBody.vue';
import TableRow from '../ui/TableRow.vue';
import TableHead from '../ui/TableHead.vue';
import TableCell from '../ui/TableCell.vue';
import Badge from '../ui/Badge.vue';
import CellValue from './CellValue.vue';

defineProps<{
  columns: string[];
  rows: Record<string, unknown>[];
  meta?: Record<string, unknown>;
}>();
</script>

// sdk/react-ui/src/components/renderers/DataTable.tsx
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell } from "../ui/Table";
import { Badge } from "../ui/Badge";

interface DataTableProps {
  columns: string[];
  rows: Record<string, unknown>[];
  meta?: Record<string, unknown>;
}

export function DataTable({ columns, rows, meta }: DataTableProps) {
  return (
    <div className="space-y-1.5">
      {meta && Object.keys(meta).length > 0 && (
        <div className="flex flex-wrap gap-1">
          {Object.entries(meta).map(([k, v]) => (
            <Badge key={k} variant="outline" className="text-[10px] font-mono">
              {k}: {String(v)}
            </Badge>
          ))}
        </div>
      )}
      <div className="max-h-72 overflow-y-auto overflow-x-auto rounded-md border">
        <Table>
          <TableHeader>
            <TableRow>
              {columns.map((col) => (
                <TableHead key={col} className="font-mono text-[11px] whitespace-nowrap">
                  {col}
                </TableHead>
              ))}
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row, i) => (
              <TableRow key={i}>
                {columns.map((col) => (
                  <TableCell key={col} className="text-[11px] font-mono">
                    <CellValue value={row[col]} />
                  </TableCell>
                ))}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}

function CellValue({ value }: { value: unknown }) {
  if (value === null || value === undefined) {
    return <span className="text-muted-foreground/40 italic">null</span>;
  }
  if (typeof value === "boolean") {
    return (
      <Badge variant={value ? "default" : "secondary"} className="text-[10px]">
        {String(value)}
      </Badge>
    );
  }
  if (typeof value === "object") {
    const s = JSON.stringify(value);
    return (
      <span className="text-muted-foreground/60" title={s}>
        {s.length > 40 ? s.slice(0, 40) + "\u2026" : s}
      </span>
    );
  }
  return <>{String(value)}</>;
}
