// sdk/vue-ui/src/components/theme/ThemeProvider.vue
<template>
  <div>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { ref, provide, watch, onMounted } from 'vue';

type Theme = 'light' | 'dark';

const props = withDefaults(
  defineProps<{
    defaultTheme?: Theme;
  }>(),
  {
    defaultTheme: 'light',
  }
);

const theme = ref<Theme>(props.defaultTheme);

const setTheme = (newTheme: Theme) => {
  theme.value = newTheme;
};

provide('theme', theme);
provide('setTheme', setTheme);

watch(
  theme,
  (newTheme) => {
    const root = document.documentElement;
    root.classList.remove('light', 'dark');
    root.classList.add(newTheme);
  },
  { immediate: true }
);

onMounted(() => {
  const root = document.documentElement;
  root.classList.remove('light', 'dark');
  root.classList.add(theme.value);
});
</script>

// sdk/react-ui/src/components/theme/ThemeProvider.tsx
import React, { createContext, useContext, useEffect, useState } from "react";

type Theme = "light" | "dark";

interface ThemeContextType {
  theme: Theme;
  setTheme: (theme: Theme) => void;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

export function ThemeProvider({
  children,
  defaultTheme = "light",
}: {
  children: React.ReactNode;
  defaultTheme?: Theme;
}) {
  const [theme, setTheme] = useState<Theme>(defaultTheme);

  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove("light", "dark");
    root.classList.add(theme);
  }, [theme]);

  return (
    <ThemeContext.Provider value={{ theme, setTheme }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  const context = useContext(ThemeContext);
  if (!context) {
    throw new Error("useTheme must be used within ThemeProvider");
  }
  return context;
}
